name: Publish to GitHub Packages

on:
  release:
    types: [published]

jobs:
  publish-github:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js for GitHub Packages
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        registry-url: 'https://npm.pkg.github.com'
        
    - name: Check npm and package-lock versions
      run: |
        echo "Node version: $(node --version)"
        echo "NPM version: $(npm --version)"
        echo "Package-lock version: $(cat package-lock.json | grep lockfileVersion)"
        
    - name: Install dependencies
      run: |
        if [ -f package-lock.json ]; then
          npm ci
        else
          npm install
        fi
      
    - name: Run tests
      run: npm test
      
    - name: Update package.json for GitHub Packages
      run: |
        sed -i 's|"name": "@odion-cloud/rockdex-db"|"name": "@odion-cloud/rockdex-db"|g' package.json
        
    - name: Publish to GitHub Packages
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }} 